#!/bin/bash

declare -a repos=(
repo
3party-repo
core-repo
pkgbuild
iso
calamares-config
xfce
wallpapers
)

for i in ${repos[@]}; do (git clone https://github.com/zone-linux/zone-${i}); done

if [[ -d "$PWD/zone-pkgbuild" ]]; then
  mv ./upd-local.sh \
     ./upd-3party.sh \
     ./upd-core.sh ./zone-pkgbuild/
fi

if [[ ! -f "$HOME/.gitconfig" ]]; then
  git config --global user.email "matthewriel63@gmail.com"
  git config --global user.name "Kungger-git"
fi
